/* Accessory list*/
export const ACCESSORY_LIST_REQUEST = 'ACCESSORY_LIST_REQUEST';
export const ACCESSORY_LIST_SUCCESS = 'ACCESSORY_LIST_SUCCESS';
export const ACCESSORY_LIST_FAIL = 'ACCESSORY_LIST_FAIL';

/*Create Accessory*/
export const CREATE_ACCESSORY_REQUEST = 'CREATE_ACCESSORY_REQUEST';
export const CREATE_ACCESSORY_SUCCESS = 'CREATE_ACCESSORY_SUCCESS';
export const CREATE_ACCESSORY_FAIL = 'CREATE_ACCESSORY_FAIL';
/*Delete Accessory*/
export const DELETE_ACCESSORY_REQUEST = 'DELETE_ACCESSORY_REQUEST';
export const DELETE_ACCESSORY_SUCCESS = 'DELETE_ACCESSORY_SUCCESS';
export const DELETE_ACCESSORY_FAIL = 'DELETE_ACCESSORY_FAIL';
/*EDIT Accessory*/
export const EDIT_ACCESSORY_REQUEST = 'EDIT_ACCESSORY_REQUEST';
export const EDIT_ACCESSORY_SUCCESS = 'EDIT_ACCESSORY_SUCCESS';
export const EDIT_ACCESSORY_FAIL = 'EDIT_ACCESSORY_FAIL';