/* Manufacturer list*/
export const ACCESSORY_LIST_REQUEST = 'ACCESSORY_LIST_REQUEST';
export const ACCESSORY_LIST_SUCCESS = 'ACCESSORY_LIST_SUCCESS';
export const ACCESSORY_LIST_FAIL = 'ACCESSORY_LIST_FAIL';