/* Customer list*/
export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST';
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS';
export const CUSTOMER_LIST_FAIL = 'CUSTOMER_LIST_FAIL';

/* Customer list*/
export const CUSTOMER_BAN_REQUEST = 'CUSTOMER_BAN_REQUEST';
export const CUSTOMER_BAN_SUCCESS = 'CUSTOMER_BAN_SUCCESS';
export const CUSTOMER_BAN_FAIL = 'CUSTOMER_BAN_FAIL';

/* NOTIFICATION list*/
export const CUSTOMER_NOTIFICATION_REQUEST = 'CUSTOMER_NOTIFICATION_REQUEST';
export const CUSTOMER_NOTIFICATION_SUCCESS = 'CUSTOMER_NOTIFICATION_SUCCESS';
export const CUSTOMER_NOTIFICATION_FAIL = 'CUSTOMER_NOTIFICATION_FAIL';
