/* Manufacturer list*/
export const MANUFACTURER_LIST_REQUEST = 'MANUFACTURER_LIST_REQUEST';
export const MANUFACTURER_LIST_SUCCESS = 'MANUFACTURER_LIST_SUCCESS';
export const MANUFACTURER_LIST_FAIL = 'MANUFACTURER_LIST_FAIL';
/* Manufacturer list All*/
export const MANUFACTURER_LIST_ALL_REQUEST = 'MANUFACTURER_LIST_ALL_REQUEST';
export const MANUFACTURER_LIST_ALL_SUCCESS = 'MANUFACTURER_LIST_ALL_SUCCESS';
export const MANUFACTURER_LIST_ALL_FAIL = 'MANUFACTURER_LIST_ALL_FAIL';
