/* Manufacturer list*/
export const MANUFACTURER_LIST_REQUEST = 'MANUFACTURER_LIST_REQUEST';
export const MANUFACTURER_LIST_SUCCESS = 'MANUFACTURER_LIST_SUCCESS';
export const MANUFACTURER_LIST_FAIL = 'MANUFACTURER_LIST_FAIL';