/* ORDER list*/
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

/* ORDER list*/
export const ORDER_STATUS_LIST_REQUEST = 'ORDER_STATUS_LIST_REQUEST';
export const ORDER_STATUS_LIST_SUCCESS = 'ORDER_STATUS_LIST_SUCCESS';
export const ORDER_STATUS_LIST_FAIL = 'ORDER_STATUS_LIST_FAIL';

/* ORDER list*/
export const ORDER_STATUS_ID_REQUEST = 'ORDER_STATUS_ID_REQUEST';
export const ORDER_STATUS_ID_SUCCESS = 'ORDER_STATUS_ID_SUCCESS';
export const ORDER_STATUS_ID_FAIL = 'ORDER_STATUS_ID_FAIL';
export const ORDER_STATUS_ID_RESET = 'ORDER_STATUS_ID_RESET';

/* ORDER payment*/
export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST';
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCCESS';
export const ORDER_PAYMENT_FAIL = 'ORDER_PAYMENT_FAIL';
/* ORDER payment done*/
