/* Package list*/
export const PACKAGE_LIST_REQUEST = 'PACKAGE_LIST_REQUEST';
export const PACKAGE_LIST_SUCCESS = 'PACKAGE_LIST_SUCCESS';
export const PACKAGE_LIST_FAIL = 'PACKAGE_LIST_FAIL';

/*Package */
export const CREATE_PACKAGE_REQUEST = 'CREATE_PACKAGE_REQUEST';
export const CREATE_PACKAGE_SUCCESS = 'CREATE_PACKAGE_SUCCESS';
export const CREATE_PACKAGE_FAIL = 'CREATE_PACKAGE_FAIL';
/*Delete PACKAGE*/
export const DELETE_PACKAGE_REQUEST = 'DELETE_PACKAGE_REQUEST';
export const DELETE_PACKAGE_SUCCESS = 'DELETE_PACKAGE_SUCCESS';
export const DELETE_PACKAGE_FAIL = 'DELETE_PACKAGE_FAIL';

/*EDIT PACKAGE*/
export const EDIT_PACKAGE_REQUEST = 'EDIT_PACKAGE_REQUEST';
export const EDIT_PACKAGE_SUCCESS = 'EDIT_PACKAGE_SUCCESS';
export const EDIT_PACKAGE_FAIL = 'EDIT_PACKAGE_FAIL';

/* Package ID*/
export const PACKAGE_ID_REQUEST = 'PACKAGE_ID_REQUEST';
export const PACKAGE_ID_SUCCESS = 'PACKAGE_ID_SUCCESS';
export const PACKAGE_ID_FAIL = 'PACKAGE_ID_FAIL';
