/* Service list*/
export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST';
export const SERVICE_LIST_SUCCESS = 'SERVICE_LIST_SUCCESS';
export const SERVICE_LIST_FAIL = 'SERVICE_LIST_FAIL';

/*Create Service*/
export const CREATE_SERVICE_REQUEST = 'CREATE_SERVICE_REQUEST';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_FAIL = 'CREATE_SERVICE_FAIL';

/* Service Type list*/
export const SERVICE_TYPE_LIST_REQUEST = 'SERVICE_TYPE_LIST_REQUEST';
export const SERVICE_TYPE_LIST_SUCCESS = 'SERVICE_TYPE_LIST_SUCCESS';
export const SERVICE_TYPE_LIST_FAIL = 'SERVICE_TYPE_LIST_FAIL';
/* Delete Serivce */
export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAIL = 'DELETE_SERVICE_FAIL';
/*EDIT Service*/
export const EDIT_SERVICE_REQUEST = 'EDIT_SERVICE_REQUEST';
export const EDIT_SERVICE_SUCCESS = 'EDIT_SERVICE_SUCCESS';
export const EDIT_SERVICE_FAIL = 'EDIT_SERVICE_FAIL';

/*Create  Service Type*/
export const CREATE_SERVICE_TYPE_REQUEST = 'CREATE_SERVICE_TYPE_REQUEST';
export const CREATE_SERVICE_TYPE_SUCCESS = 'CREATE_SERVICE_TYPE_SUCCESS';
export const CREATE_SERVICE_TYPE_FAIL = 'CREATE_SERVICE_TYPE_FAIL';

/*Create  COUPON */
export const CREATE_COUPON_REQUEST = 'CREATE_COUPON_REQUEST';
export const CREATE_COUPON_SUCCESS = 'CREATE_COUPON_SUCCESS';
export const CREATE_COUPON_FAIL = 'CREATE_COUPON_FAIL';
