/* TRANSACTION list*/
export const TRANSACTION_LIST_REQUEST = 'TRANSACTION_LIST_REQUEST';
export const TRANSACTION_LIST_SUCCESS = 'TRANSACTION_LIST_SUCCESS';
export const TRANSACTION_LIST_FAIL = 'TRANSACTION_LIST_FAIL';

/* TRANSACTION all list*/
export const TRANSACTION_ALL_LIST_REQUEST = 'TRANSACTION_ALL_LIST_REQUEST';
export const TRANSACTION_ALL_LIST_SUCCESS = 'TRANSACTION_ALL_LIST_SUCCESS';
export const TRANSACTION_ALL_LIST_FAIL = 'TRANSACTION_ALL_LIST_FAIL';
