/*User */
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

/*Employee */
export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST';
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS';
export const EMPLOYEE_LIST_FAIL = 'EMPLOYEE_LIST_FAIL';

/*Create employee*/
export const CREATE_EMPLOYEE_REQUEST = 'CREATE_EMPLOYEE_REQUEST';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_FAIL = 'CREATE_EMPLOYEE_FAIL';

/*Delete employee*/
export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAIL = 'DELETE_EMPLOYEE_FAIL';

/*EDIT employee*/
export const EDIT_EMPLOYEE_REQUEST = 'EDIT_EMPLOYEE_REQUEST';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_FAIL = 'EDIT_EMPLOYEE_FAIL';

/*Trigger reload*/
export const TRIGGER_RELOAD = 'TRIGGER_RELOAD';

/*Employee  absent list*/
export const EMPLOYEE_ABSENT_LIST_REQUEST = 'EMPLOYEE_ABSENT_LIST_REQUEST';
export const EMPLOYEE_ABSENT_LIST_SUCCESS = 'EMPLOYEE_ABSENT_LIST_SUCCESS';
export const EMPLOYEE_ABSENT_LIST_FAIL = 'EMPLOYEE_ABSENT_LIST_FAIL';
